### ISSUE TITLE
Exception calling Playsync

### ISSUE THREAD

**Issue by Red88Rex** [PheonixMMKC777/Final_Fantasy_2_Randomizer#2]
Hi, I'm running into this error, regardless of powershell or .exe - 

Players=Sprites

All OK

ERROR: Exception calling "PlaySync" with "0" argument (s): "Please be sure a sound file exists at the specified location."

Do you know what I am missing or doing wrong? I can launch the randomizer and select stuff, but when I click "import", this error comes up and I can't continue. Thanks

**Comment by PheonixMMKC777** [comment]
So it was a very small oversight, it was looking for a specific sound file to play on completion but I just did away with it.
It should build the ROM regardless of the sound playing though.
This has been fixed and is in the newest release
